/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEWADM;

import VIEWCliente.Home;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.DAO.ProdutoDAO;
import model.bean.Produto;

/**
 *
 * @author Trocar
 */
public final class CadastrarProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarProduto
     */
    public CadastrarProduto() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabelaProdutos.getModel();
        tabelaProdutos.setRowSorter(new TableRowSorter(modelo));
        
        
        readJTable();
    }
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel)tabelaProdutos.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        for (Produto p : pdao.read()) {
            modelo.addRow(new Object[]{
            p.getID(),
            p.getNome(),
            p.getValor(),
            p.getSabor(),
            p.getTamanho(),
            p.getDescricao(),
            p.getQtde_estoque(),
            p.getDisponivel()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stringNome = new javax.swing.JTextField();
        doubleValor = new javax.swing.JTextField();
        stringDescricao = new javax.swing.JTextField();
        stringSabor = new javax.swing.JTextField();
        stringTamanho = new javax.swing.JTextField();
        intQtde = new javax.swing.JTextField();
        stringDisponivel = new javax.swing.JTextField();
        botaoSair = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        botãoCadastrar = new javax.swing.JButton();
        excluirBotao = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro Produto");

        stringNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        doubleValor.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor"));

        stringDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));

        stringSabor.setBorder(javax.swing.BorderFactory.createTitledBorder("Sabor"));

        stringTamanho.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamanho"));

        intQtde.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade estoque"));
        intQtde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intQtdeActionPerformed(evt);
            }
        });

        stringDisponivel.setBorder(javax.swing.BorderFactory.createTitledBorder("Disponível?"));

        botaoSair.setText("Voltar");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "VALOR", "SABOR", "TAMANHO", "DESCRIÇÃO", "QTDE_EM_ESTOQUE", "DISPONÍVEL?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        tabelaProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaProdutosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        botãoCadastrar.setText("Cadastrar");
        botãoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botãoCadastrarActionPerformed(evt);
            }
        });

        excluirBotao.setText("Deletar");
        excluirBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(stringDisponivel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stringDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stringTamanho, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stringSabor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doubleValor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stringNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botãoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(excluirBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(intQtde, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(stringNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doubleValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stringSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stringTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stringDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stringDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSair)
                    .addComponent(botaoAlterar)
                    .addComponent(botãoCadastrar)
                    .addComponent(excluirBotao))
                .addGap(51, 51, 51))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void intQtdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intQtdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intQtdeActionPerformed

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        // TODO add your handling code here:
        if (tabelaProdutos.getSelectedRow() != -1) {
            Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        p.setNome(stringNome.getText());
        p.setValor(Double.parseDouble(doubleValor.getText()));
        p.setSabor(stringSabor.getText());
        p.setTamanho(stringTamanho.getText());
        p.setDescricao(stringDescricao.getText());
        p.setQtde_estoque(Integer.parseInt(intQtde.getText()));
        p.setDisponivel(stringDisponivel.getText());
        p.setID((int)tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0));
        
        dao.update(p);
        
        stringNome.setText("");
        doubleValor.setText("");
        stringSabor.setText("");
        stringTamanho.setText("");
        stringDescricao.setText("");
        intQtde.setText("");
        stringDisponivel.setText(""); 
        
        readJTable();
        }
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botãoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botãoCadastrarActionPerformed
        // TODO add your handling code here:
        Produto p = new Produto();
        ProdutoDAO dao = new ProdutoDAO();
        p.setNome(stringNome.getText());
        p.setValor(Double.parseDouble(doubleValor.getText()));
        p.setSabor(stringSabor.getText());
        p.setTamanho(stringTamanho.getText());
        p.setDescricao(stringDescricao.getText());
        p.setQtde_estoque(Integer.parseInt(intQtde.getText()));
        p.setDisponivel(stringDisponivel.getText());
        
        dao.create(p);
        
        stringNome.setText("");
        doubleValor.setText("");
        stringSabor.setText("");
        stringTamanho.setText("");
        stringDescricao.setText("");
        intQtde.setText("");
        stringDisponivel.setText("");
        
        readJTable();
    }//GEN-LAST:event_botãoCadastrarActionPerformed

    private void tabelaProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaProdutosKeyReleased
        // TODO add your handling code here:
        if (tabelaProdutos.getSelectedRow() != -1) {

            stringNome.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 1).toString());
            doubleValor.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 2).toString());
            stringSabor.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 3).toString());
            stringTamanho.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 4).toString());
            stringDescricao.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 5).toString());
            intQtde.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 6).toString());
            stringDisponivel.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 7).toString());
            

        }

    }//GEN-LAST:event_tabelaProdutosKeyReleased

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        // TODO add your handling code here:
        if (tabelaProdutos.getSelectedRow() != -1) {

            stringNome.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 1).toString());
            doubleValor.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 2).toString());
            stringSabor.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 3).toString());
            stringTamanho.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 4).toString());
            stringDescricao.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 5).toString());
            intQtde.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 6).toString());
            stringDisponivel.setText(tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 7).toString());
            

        }
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void excluirBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBotaoActionPerformed
        // TODO add your handling code here:
        if (tabelaProdutos.getSelectedRow() != -1){
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();
            p.setID((int)tabelaProdutos.getValueAt(tabelaProdutos.getSelectedRow(), 0));
            dao.delete(p);
            stringNome.setText("");
            doubleValor.setText("");
            stringSabor.setText("");
            stringTamanho.setText("");
            stringDescricao.setText("");
            intQtde.setText("");
            stringDisponivel.setText("");
        
        readJTable();
        }else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir");
        }
    }//GEN-LAST:event_excluirBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastrarProduto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botãoCadastrar;
    private javax.swing.JTextField doubleValor;
    private javax.swing.JButton excluirBotao;
    private javax.swing.JTextField intQtde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stringDescricao;
    private javax.swing.JTextField stringDisponivel;
    private javax.swing.JTextField stringNome;
    private javax.swing.JTextField stringSabor;
    private javax.swing.JTextField stringTamanho;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables

    
}
